2025-04-17 10:50:22,970 - [Rank0] #################################################################
2025-04-17 10:50:22,970 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 10:50:23,117 - [Rank0] User network built successfully.
2025-04-17 10:50:23,650 - [Rank0] ERROR: !stack.empty() INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/autograd/profiler_python.cpp":983, please report a bug to PyTorch. Python replay stack is empty.
2025-04-17 10:50:23,652 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 102, in <module>
    prof.step()
  File "/home/alvaro/venvs/edlut/lib/python3.12/site-packages/torch/profiler/profiler.py", line 821, in step
    self._transit_action(prev_action, self.current_action)
  File "/home/alvaro/venvs/edlut/lib/python3.12/site-packages/torch/profiler/profiler.py", line 852, in _transit_action
    action()
  File "/home/alvaro/venvs/edlut/lib/python3.12/site-packages/torch/profiler/profiler.py", line 239, in stop_trace
    self.profiler.__exit__(None, None, None)
  File "/home/alvaro/venvs/edlut/lib/python3.12/site-packages/torch/autograd/profiler.py", line 378, in __exit__
    self.kineto_results = _disable_profiler()
                          ^^^^^^^^^^^^^^^^^^^
RuntimeError: !stack.empty() INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/autograd/profiler_python.cpp":983, please report a bug to PyTorch. Python replay stack is empty.

2025-04-17 10:52:24,434 - [Rank0] #################################################################
2025-04-17 10:52:24,435 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 10:52:24,574 - [Rank0] User network built successfully.
2025-04-17 10:52:52,950 - [Rank0] #################################################################
2025-04-17 10:52:52,951 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 10:52:53,066 - [Rank0] User network built successfully.
2025-04-17 10:52:53,539 - [Rank0] ERROR: !stack.empty() INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/autograd/profiler_python.cpp":983, please report a bug to PyTorch. Python replay stack is empty.
2025-04-17 10:52:53,541 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 102, in <module>
    prof.step()
  File "/home/alvaro/venvs/edlut/lib/python3.12/site-packages/torch/profiler/profiler.py", line 821, in step
    self._transit_action(prev_action, self.current_action)
  File "/home/alvaro/venvs/edlut/lib/python3.12/site-packages/torch/profiler/profiler.py", line 852, in _transit_action
    action()
  File "/home/alvaro/venvs/edlut/lib/python3.12/site-packages/torch/profiler/profiler.py", line 239, in stop_trace
    self.profiler.__exit__(None, None, None)
  File "/home/alvaro/venvs/edlut/lib/python3.12/site-packages/torch/autograd/profiler.py", line 378, in __exit__
    self.kineto_results = _disable_profiler()
                          ^^^^^^^^^^^^^^^^^^^
RuntimeError: !stack.empty() INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/autograd/profiler_python.cpp":983, please report a bug to PyTorch. Python replay stack is empty.

2025-04-17 10:57:07,703 - [Rank0] #################################################################
2025-04-17 10:57:07,703 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 10:57:07,821 - [Rank0] User network built successfully.
2025-04-17 12:03:12,503 - [Rank0] #################################################################
2025-04-17 12:03:12,503 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 12:03:12,639 - [Rank0] User network built successfully.
2025-04-17 12:03:18,281 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-17 12:03:18,883 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-17 12:03:19,184 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-17 12:03:53,160 - [Rank0] #################################################################
2025-04-17 12:03:53,160 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 12:03:53,256 - [Rank0] User network built successfully.
2025-04-17 12:03:59,237 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-17 12:03:59,671 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-17 12:03:59,874 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-17 12:08:50,924 - [Rank0] #################################################################
2025-04-17 12:08:50,924 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 12:08:51,028 - [Rank0] User network built successfully.
2025-04-17 12:08:57,263 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-17 12:08:57,706 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-17 12:08:57,935 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-17 12:11:07,816 - [Rank0] #################################################################
2025-04-17 12:11:07,817 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 12:11:07,965 - [Rank0] User network built successfully.
2025-04-17 12:11:15,335 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-17 12:11:15,776 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-17 12:11:15,977 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-17 14:39:06,270 - [Rank0] #################################################################
2025-04-17 14:39:06,270 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 14:39:06,441 - [Rank0] User network built successfully.
2025-04-17 14:39:13,723 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-17 14:39:14,166 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-17 14:39:14,369 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-17 15:19:52,153 - [Rank0] #################################################################
2025-04-17 15:19:52,153 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 15:19:52,275 - [Rank0] User network built successfully.
2025-04-17 15:19:59,487 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-17 15:19:59,914 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-17 15:20:00,115 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-17 15:20:24,090 - [Rank0] #################################################################
2025-04-17 15:20:24,090 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 15:20:24,220 - [Rank0] User network built successfully.
2025-04-17 15:20:31,639 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-17 15:20:32,071 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-17 15:20:32,305 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-17 15:34:40,353 - [Rank0] #################################################################
2025-04-17 15:34:40,353 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 15:34:40,421 - [Rank0] User network built successfully.
2025-04-17 15:34:40,577 - [Rank0] ERROR: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-04-17 15:34:40,578 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 1005, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 452, in _process
    self._update_active_indices()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 463, in _update_active_indices
    self._spiked = torch.where(spikes)[0]
RuntimeError: CUDA error: operation not permitted when stream is capturing
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_01_multipleGPUs.py", line 67, in <module>
    with PingPongRingSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 926, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 1004, in initialize
    with torch.cuda.graph(self.local_circuit.graph, stream=self.local_circuit.graph_stream):
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-04-17 15:34:55,134 - [Rank0] #################################################################
2025-04-17 15:34:55,134 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 15:34:55,184 - [Rank0] User network built successfully.
2025-04-17 15:34:55,321 - [Rank0] ERROR: CUDA error: operation failed due to a previous error during capture
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-04-17 15:34:55,322 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 1005, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 452, in _process
    self._update_active_indices()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 463, in _update_active_indices
    self._spiked = torch.where(spikes)[0]
RuntimeError: CUDA error: operation not permitted when stream is capturing
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_01_multipleGPUs.py", line 67, in <module>
    with PingPongRingSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 926, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 1004, in initialize
    with torch.cuda.graph(self.local_circuit.graph, stream=self.local_circuit.graph_stream):
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-04-17 15:35:21,396 - [Rank0] #################################################################
2025-04-17 15:35:21,396 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 15:35:21,461 - [Rank0] User network built successfully.
2025-04-17 15:35:21,619 - [Rank0] ERROR: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-04-17 15:35:21,620 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 1005, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 452, in _process
    self._update_active_indices()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 463, in _update_active_indices
    self._spiked = torch.where(spikes)[0]
RuntimeError: CUDA error: operation not permitted when stream is capturing
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_01_multipleGPUs.py", line 67, in <module>
    with PingPongRingSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 926, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 1004, in initialize
    with torch.cuda.graph(self.local_circuit.graph, stream=self.local_circuit.graph_stream):
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-04-17 15:46:25,032 - [Rank0] #################################################################
2025-04-17 15:46:25,032 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 15:46:25,116 - [Rank0] User network built successfully.
2025-04-17 15:46:25,304 - [Rank0] ERROR: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-04-17 15:46:25,305 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 1010, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 454, in _process
    self._update_active_indices()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 465, in _update_active_indices
    num = torch.nonzero(spikes, as_tuple=False, out=self._spiked_idx.unsqueeze(1))
RuntimeError: CUDA error: operation not permitted when stream is capturing
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_01_multipleGPUs.py", line 67, in <module>
    with PingPongRingSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 931, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 1009, in initialize
    with torch.cuda.graph(self.local_circuit.graph, stream=self.local_circuit.graph_stream):
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-04-17 15:52:38,191 - [Rank0] #################################################################
2025-04-17 15:52:38,191 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 15:52:38,244 - [Rank0] User network built successfully.
2025-04-17 15:52:38,385 - [Rank0] ERROR: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-04-17 15:52:38,385 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 984, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 459, in _process
    self._update_active_indices()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 470, in _update_active_indices
    num = torch.nonzero(spikes, as_tuple=False, out=self._spiked_idx.unsqueeze(1))
RuntimeError: CUDA error: operation not permitted when stream is capturing
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_01_multipleGPUs.py", line 67, in <module>
    with PingPongRingSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 905, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 983, in initialize
    with torch.cuda.graph(self.local_circuit.graph, stream=self.local_circuit.graph_stream):
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-04-17 23:47:20,963 - [Rank0] #################################################################
2025-04-17 23:47:20,963 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 23:47:21,022 - [Rank0] User network built successfully.
2025-04-17 23:47:21,927 - [Rank0] Gráfico guardado como 'rank0_output.png'
2025-04-17 23:55:25,527 - [Rank0] #################################################################
2025-04-17 23:55:25,528 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 23:55:25,604 - [Rank0] User network built successfully.
2025-04-17 23:55:25,772 - [Rank0] ERROR: CUDA error: operation failed due to a previous error during capture
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-04-17 23:55:25,772 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 968, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 455, in _process
    self._update()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 549, in _update
    self.x_pre[self.idx_pre[pre_spikes]] += 1.0
RuntimeError: CUDA error: operation not permitted when stream is capturing
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 87, in <module>
    with RandomInputSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 889, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 967, in initialize
    with torch.cuda.graph(self.local_circuit.graph, stream=self.local_circuit.graph_stream):
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-04-17 23:55:54,567 - [Rank0] #################################################################
2025-04-17 23:55:54,567 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 23:55:54,637 - [Rank0] User network built successfully.
2025-04-17 23:55:54,809 - [Rank0] ERROR: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-04-17 23:55:54,810 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 968, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 455, in _process
    self._update()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 549, in _update
    self.x_pre[self.idx_pre[pre_spikes]] += 1.0
RuntimeError: CUDA error: operation not permitted when stream is capturing
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 87, in <module>
    with RandomInputSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 889, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 967, in initialize
    with torch.cuda.graph(self.local_circuit.graph, stream=self.local_circuit.graph_stream):
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-04-17 23:58:34,980 - [Rank0] #################################################################
2025-04-17 23:58:34,981 - [Rank0] Neurobridge initialized. Building user network...
2025-04-17 23:58:35,077 - [Rank0] User network built successfully.
2025-04-17 23:58:35,226 - [Rank0] ERROR: The shape of the mask [1210000] at index 0 does not match the shape of the indexed tensor [1000] at index 0
2025-04-17 23:58:35,226 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 87, in <module>
    with RandomInputSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 885, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 960, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 455, in _process
    self._update()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 549, in _update
    self.x_pre[pre_spikes] += 1.0
IndexError: The shape of the mask [1210000] at index 0 does not match the shape of the indexed tensor [1000] at index 0

2025-04-18 00:00:59,701 - [Rank0] #################################################################
2025-04-18 00:00:59,701 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 00:00:59,796 - [Rank0] User network built successfully.
2025-04-18 00:01:00,025 - [Rank0] ERROR: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-04-18 00:01:00,027 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 968, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 455, in _process
    self._update()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 549, in _update
    self.x_pre[self.idx_pre[pre_spikes]] += 1.0
RuntimeError: CUDA error: operation not permitted when stream is capturing
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 87, in <module>
    with RandomInputSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 889, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 967, in initialize
    with torch.cuda.graph(self.local_circuit.graph, stream=self.local_circuit.graph_stream):
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-04-18 00:01:39,957 - [Rank0] #################################################################
2025-04-18 00:01:39,957 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 00:01:40,033 - [Rank0] User network built successfully.
2025-04-18 00:01:40,230 - [Rank0] ERROR: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-04-18 00:01:40,231 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 970, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 455, in _process
    self._update()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 549, in _update
    mask = self.idx_pre[pre_spikes]
RuntimeError: CUDA error: operation not permitted when stream is capturing
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 87, in <module>
    with RandomInputSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 891, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 969, in initialize
    with torch.cuda.graph(self.local_circuit.graph, stream=self.local_circuit.graph_stream):
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-04-18 00:05:10,279 - [Rank0] #################################################################
2025-04-18 00:05:10,279 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 00:05:10,359 - [Rank0] User network built successfully.
2025-04-18 00:05:10,465 - [Rank0] ERROR: The shape of the mask [1210000] at index 0 does not match the shape of the indexed tensor [1000] at index 0
2025-04-18 00:05:10,465 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 87, in <module>
    with RandomInputSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 889, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 964, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 455, in _process
    self._update()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 549, in _update
    self.x_pre[pre_spikes] += 1.0
IndexError: The shape of the mask [1210000] at index 0 does not match the shape of the indexed tensor [1000] at index 0

2025-04-18 00:08:56,533 - [Rank0] #################################################################
2025-04-18 00:08:56,533 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 00:08:56,607 - [Rank0] User network built successfully.
2025-04-18 00:08:56,782 - [Rank0] ERROR: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2025-04-18 00:08:56,782 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 964, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 455, in _process
    self._update()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 549, in _update
    self.x_pre[pre_spikes] += 1.0
RuntimeError: CUDA error: operation not permitted when stream is capturing
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 87, in <module>
    with RandomInputSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 885, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 963, in initialize
    with torch.cuda.graph(self.local_circuit.graph, stream=self.local_circuit.graph_stream):
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/home/alvaro/venvs/torch/lib/python3.10/site-packages/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-04-18 00:09:39,907 - [Rank0] #################################################################
2025-04-18 00:09:39,907 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 00:09:40,023 - [Rank0] User network built successfully.
2025-04-18 00:15:56,854 - [Rank0] #################################################################
2025-04-18 00:15:56,854 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 00:15:56,937 - [Rank0] User network built successfully.
2025-04-18 00:15:57,038 - [Rank0] ERROR: index_add_(): self (Half) and source (Float) must have the same scalar type
2025-04-18 00:15:57,039 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 87, in <module>
    with RandomInputSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 885, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 960, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 454, in _process
    self._propagate()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 463, in _propagate
    self._current_buffer.index_add_(0, self.idx_pos, contrib)
RuntimeError: index_add_(): self (Half) and source (Float) must have the same scalar type

2025-04-18 00:16:54,399 - [Rank0] #################################################################
2025-04-18 00:16:54,399 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 00:16:54,495 - [Rank0] User network built successfully.
2025-04-18 00:16:54,633 - [Rank0] ERROR: index_add_(): self (Half) and source (Float) must have the same scalar type
2025-04-18 00:16:54,634 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 87, in <module>
    with RandomInputSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 885, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 960, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 454, in _process
    self._propagate()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 463, in _propagate
    self._current_buffer.index_add_(0, self.idx_pos, contrib)
RuntimeError: index_add_(): self (Half) and source (Float) must have the same scalar type

2025-04-18 00:56:55,602 - [Rank0] #################################################################
2025-04-18 00:56:55,602 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 00:56:55,676 - [Rank0] User network built successfully.
2025-04-18 00:56:55,781 - [Rank0] ERROR: index_add_(): self (Half) and source (Float) must have the same scalar type
2025-04-18 00:56:55,782 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 87, in <module>
    with RandomInputSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 885, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 960, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 454, in _process
    self._propagate()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 463, in _propagate
    self._current_buffer.index_add_(0, self.idx_pos, contrib)
RuntimeError: index_add_(): self (Half) and source (Float) must have the same scalar type

2025-04-18 00:57:52,613 - [Rank0] #################################################################
2025-04-18 00:57:52,613 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 00:57:52,677 - [Rank0] User network built successfully.
2025-04-18 00:58:07,966 - [Rank0] #################################################################
2025-04-18 00:58:07,966 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 00:58:08,036 - [Rank0] User network built successfully.
2025-04-18 00:59:04,074 - [Rank0] #################################################################
2025-04-18 00:59:04,074 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 00:59:04,141 - [Rank0] User network built successfully.
2025-04-18 00:59:04,327 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 00:59:04,805 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-18 01:00:33,999 - [Rank0] #################################################################
2025-04-18 01:00:34,000 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 01:00:34,057 - [Rank0] User network built successfully.
2025-04-18 01:00:46,799 - [Rank0] #################################################################
2025-04-18 01:00:46,799 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 01:00:46,865 - [Rank0] User network built successfully.
2025-04-18 01:03:06,457 - [Rank0] #################################################################
2025-04-18 01:03:06,457 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 01:03:06,555 - [Rank0] User network built successfully.
2025-04-18 01:04:17,008 - [Rank0] #################################################################
2025-04-18 01:04:17,008 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 01:04:17,076 - [Rank0] User network built successfully.
2025-04-18 01:04:40,408 - [Rank0] #################################################################
2025-04-18 01:04:40,408 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 01:04:40,492 - [Rank0] User network built successfully.
2025-04-18 09:13:02,243 - [Rank0] #################################################################
2025-04-18 09:13:02,243 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:13:02,310 - [Rank0] User network built successfully.
2025-04-18 09:13:02,344 - [Rank0] ERROR: tensors used as indices must be long, int, byte or bool tensors
2025-04-18 09:13:02,345 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 105, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 968, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 285, in _process
    self._spike_buffer[:, t_idx] = spikes
IndexError: tensors used as indices must be long, int, byte or bool tensors

2025-04-18 09:14:42,606 - [Rank0] #################################################################
2025-04-18 09:14:42,606 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:14:42,673 - [Rank0] User network built successfully.
2025-04-18 09:14:42,706 - [Rank0] ERROR: tensors used as indices must be long, int, byte or bool tensors
2025-04-18 09:14:42,706 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 105, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 968, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 285, in _process
    self._spike_buffer[:, t_idx] = spikes
IndexError: tensors used as indices must be long, int, byte or bool tensors

2025-04-18 09:15:21,936 - [Rank0] #################################################################
2025-04-18 09:15:21,936 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:15:22,006 - [Rank0] User network built successfully.
2025-04-18 09:15:22,037 - [Rank0] ERROR: tensors used as indices must be long, int, byte or bool tensors
2025-04-18 09:15:22,037 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 105, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 969, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 286, in _process
    self._spike_buffer[:, t_idx] = spikes
IndexError: tensors used as indices must be long, int, byte or bool tensors

2025-04-18 09:15:43,821 - [Rank0] #################################################################
2025-04-18 09:15:43,821 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:15:43,884 - [Rank0] User network built successfully.
2025-04-18 09:15:43,917 - [Rank0] ERROR: tensors used as indices must be long, int, byte or bool tensors
2025-04-18 09:15:43,918 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 105, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 969, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 286, in _process
    self._spike_buffer[:, t_idx] = spikes
IndexError: tensors used as indices must be long, int, byte or bool tensors

2025-04-18 09:16:59,711 - [Rank0] #################################################################
2025-04-18 09:16:59,712 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:16:59,776 - [Rank0] User network built successfully.
2025-04-18 09:16:59,811 - [Rank0] ERROR: tensors used as indices must be long, int, byte or bool tensors
2025-04-18 09:16:59,812 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 105, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 971, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 288, in _process
    self._spike_buffer[:, t_idx] = spikes
IndexError: tensors used as indices must be long, int, byte or bool tensors

2025-04-18 09:17:32,733 - [Rank0] #################################################################
2025-04-18 09:17:32,733 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:17:32,802 - [Rank0] User network built successfully.
2025-04-18 09:17:32,832 - [Rank0] ERROR: shape mismatch: value tensor of shape [1000] cannot be broadcast to indexing result of shape [1000, 1]
2025-04-18 09:17:32,832 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 105, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 968, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 285, in _process
    self._spike_buffer[:, t_idx] = spikes
RuntimeError: shape mismatch: value tensor of shape [1000] cannot be broadcast to indexing result of shape [1000, 1]

2025-04-18 09:18:34,462 - [Rank0] #################################################################
2025-04-18 09:18:34,462 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:18:34,532 - [Rank0] User network built successfully.
2025-04-18 09:18:34,565 - [Rank0] ERROR: shape mismatch: value tensor of shape [1000] cannot be broadcast to indexing result of shape [1000, 1]
2025-04-18 09:18:34,565 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 105, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 972, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 289, in _process
    self._spike_buffer[:, t_idx] = spikes
RuntimeError: shape mismatch: value tensor of shape [1000] cannot be broadcast to indexing result of shape [1000, 1]

2025-04-18 09:19:06,216 - [Rank0] #################################################################
2025-04-18 09:19:06,216 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:19:06,281 - [Rank0] User network built successfully.
2025-04-18 09:19:06,313 - [Rank0] ERROR: shape mismatch: value tensor of shape [1210] cannot be broadcast to indexing result of shape [1210, 1]
2025-04-18 09:19:06,314 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 105, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 968, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 260, in _process
    self._spike_buffer[:, t_idx] = spikes
RuntimeError: shape mismatch: value tensor of shape [1210] cannot be broadcast to indexing result of shape [1210, 1]

2025-04-18 09:19:21,824 - [Rank0] #################################################################
2025-04-18 09:19:21,824 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:19:21,888 - [Rank0] User network built successfully.
2025-04-18 09:19:22,861 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 09:19:23,017 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-18 09:19:23,158 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-18 09:20:35,138 - [Rank0] #################################################################
2025-04-18 09:20:35,138 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:20:35,209 - [Rank0] User network built successfully.
2025-04-18 09:20:44,895 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 09:20:45,274 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-18 09:20:45,450 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-18 09:21:30,769 - [Rank0] #################################################################
2025-04-18 09:21:30,770 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:21:30,834 - [Rank0] User network built successfully.
2025-04-18 09:21:30,980 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 09:21:31,429 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-18 09:22:21,310 - [Rank0] #################################################################
2025-04-18 09:22:21,310 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:22:21,394 - [Rank0] User network built successfully.
2025-04-18 09:22:29,553 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 09:22:29,933 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-18 09:22:30,110 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-18 09:28:45,584 - [Rank0] #################################################################
2025-04-18 09:28:45,584 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:28:45,635 - [Rank0] User network built successfully.
2025-04-18 09:33:22,154 - [Rank0] #################################################################
2025-04-18 09:33:22,154 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:33:22,155 - [Rank0] ERROR: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number
2025-04-18 09:33:22,156 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 88, in <module>
    with RandomInputSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 937, in __init__
    self.build_user_network(self.rank, self.world_size)
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 22, in build_user_network
    src_neurons = RandomSpikeGenerator(
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 275, in __init__
    super().__init__(device, n_neurons, spatial_dimensions=spatial_dimensions, delay_max=delay_max)
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 167, in __init__
    super().__init__(device, n_neurons, spatial_dimensions)
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 133, in __init__
    super().__init__(device, size)
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 102, in __init__
    self.filter = torch.ones(self.size[0], dtype=torch.bool, device=self.device)
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

2025-04-18 09:33:53,554 - [Rank0] #################################################################
2025-04-18 09:33:53,554 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:33:53,564 - [Rank0] ERROR: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number
2025-04-18 09:33:53,565 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 88, in <module>
    with RandomInputSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 937, in __init__
    self.build_user_network(self.rank, self.world_size)
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 22, in build_user_network
    src_neurons = RandomSpikeGenerator(
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 275, in __init__
    super().__init__(device, n_neurons, spatial_dimensions=spatial_dimensions, delay_max=delay_max)
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 167, in __init__
    super().__init__(device, n_neurons, spatial_dimensions)
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 135, in __init__
    self.positions = torch.randn((self.size[0], self.spatial_dimensions[0]), device=self.device)
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

2025-04-18 09:34:49,776 - [Rank0] #################################################################
2025-04-18 09:34:49,777 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:34:49,837 - [Rank0] User network built successfully.
2025-04-18 09:50:45,948 - [Rank0] #################################################################
2025-04-18 09:50:45,948 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:50:46,002 - [Rank0] User network built successfully.
2025-04-18 09:57:55,429 - [Rank0] #################################################################
2025-04-18 09:57:55,429 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:57:55,488 - [Rank0] User network built successfully.
2025-04-18 09:57:55,524 - [Rank0] ERROR: index_copy_(): Expected a long tensor for index, but got Int
2025-04-18 09:57:55,524 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 105, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 971, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 288, in _process
    self._spike_buffer.index_copy_(1, t_idx, spikes.unsqueeze(1))
RuntimeError: index_copy_(): Expected a long tensor for index, but got Int

2025-04-18 09:58:27,005 - [Rank0] #################################################################
2025-04-18 09:58:27,005 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:58:27,054 - [Rank0] User network built successfully.
2025-04-18 09:58:27,089 - [Rank0] ERROR: index_copy_(): Expected a long tensor for index, but got Int
2025-04-18 09:58:27,089 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 105, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 973, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 290, in _process
    self._spike_buffer.index_copy_(1, t_idx, spikes.unsqueeze(1))
RuntimeError: index_copy_(): Expected a long tensor for index, but got Int

2025-04-18 09:59:53,177 - [Rank0] #################################################################
2025-04-18 09:59:53,177 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 09:59:53,243 - [Rank0] User network built successfully.
2025-04-18 10:06:03,159 - [Rank0] #################################################################
2025-04-18 10:06:03,160 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:06:03,224 - [Rank0] User network built successfully.
2025-04-18 10:06:03,261 - [Rank0] ERROR: index_copy_(): Expected a long tensor for index, but got Int
2025-04-18 10:06:03,261 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 105, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 970, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 287, in _process
    self._spike_buffer.index_copy_(1, t_idx, spikes.unsqueeze(1))
RuntimeError: index_copy_(): Expected a long tensor for index, but got Int

2025-04-18 10:07:25,448 - [Rank0] #################################################################
2025-04-18 10:07:25,448 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:07:25,501 - [Rank0] User network built successfully.
2025-04-18 10:07:25,528 - [Rank0] ERROR: index_copy_(): Expected a long tensor for index, but got Int
2025-04-18 10:07:25,529 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 105, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 971, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 288, in _process
    self._spike_buffer.index_copy_(1, t_idx, spikes.unsqueeze(1))
RuntimeError: index_copy_(): Expected a long tensor for index, but got Int

2025-04-18 10:07:39,290 - [Rank0] #################################################################
2025-04-18 10:07:39,290 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:07:39,349 - [Rank0] User network built successfully.
2025-04-18 10:07:39,377 - [Rank0] ERROR: index_copy_(): Expected a long tensor for index, but got Int
2025-04-18 10:07:39,378 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 105, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 972, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 289, in _process
    self._spike_buffer.index_copy_(1, t_idx, spikes.unsqueeze(1))
RuntimeError: index_copy_(): Expected a long tensor for index, but got Int

2025-04-18 10:08:21,985 - [Rank0] #################################################################
2025-04-18 10:08:21,985 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:08:22,041 - [Rank0] User network built successfully.
2025-04-18 10:08:34,717 - [Rank0] #################################################################
2025-04-18 10:08:34,717 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:08:34,772 - [Rank0] User network built successfully.
2025-04-18 10:12:48,191 - [Rank0] #################################################################
2025-04-18 10:12:48,191 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:12:48,243 - [Rank0] User network built successfully.
2025-04-18 10:12:48,298 - [Rank0] ERROR: index_fill_(): Expected dtype int64 for index.
2025-04-18 10:12:48,298 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 105, in <module>
    engine.step()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 970, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 77, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 78, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 261, in _process
    self.V.index_fill_(0, spikes, 0.0) # Reset membrane potential
IndexError: index_fill_(): Expected dtype int64 for index.

2025-04-18 10:13:27,642 - [Rank0] #################################################################
2025-04-18 10:13:27,643 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:13:27,709 - [Rank0] User network built successfully.
2025-04-18 10:19:32,464 - [Rank0] #################################################################
2025-04-18 10:19:32,464 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:19:32,521 - [Rank0] User network built successfully.
2025-04-18 10:33:36,395 - [Rank0] #################################################################
2025-04-18 10:33:36,396 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:33:36,460 - [Rank0] User network built successfully.
2025-04-18 10:33:44,352 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 10:33:44,726 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-18 10:33:44,900 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-18 10:35:10,984 - [Rank0] #################################################################
2025-04-18 10:35:10,985 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:35:11,063 - [Rank0] User network built successfully.
2025-04-18 10:35:18,998 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 10:35:19,396 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-18 10:35:19,615 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-18 10:35:25,317 - [Rank0] #################################################################
2025-04-18 10:35:25,317 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:35:25,367 - [Rank0] User network built successfully.
2025-04-18 10:36:07,877 - [Rank0] #################################################################
2025-04-18 10:36:07,878 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:36:07,927 - [Rank0] User network built successfully.
2025-04-18 10:39:23,319 - [Rank0] #################################################################
2025-04-18 10:39:23,319 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:39:23,392 - [Rank0] User network built successfully.
2025-04-18 10:40:32,370 - [Rank0] #################################################################
2025-04-18 10:40:32,370 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:40:32,419 - [Rank0] User network built successfully.
2025-04-18 10:43:24,327 - [Rank0] #################################################################
2025-04-18 10:43:24,327 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:43:24,376 - [Rank0] User network built successfully.
2025-04-18 10:43:41,941 - [Rank0] #################################################################
2025-04-18 10:43:41,941 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:43:41,990 - [Rank0] User network built successfully.
2025-04-18 10:44:52,052 - [Rank0] #################################################################
2025-04-18 10:44:52,052 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:44:52,101 - [Rank0] User network built successfully.
2025-04-18 10:45:00,020 - [Rank0] #################################################################
2025-04-18 10:45:00,020 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:45:00,071 - [Rank0] User network built successfully.
2025-04-18 10:45:29,950 - [Rank0] #################################################################
2025-04-18 10:45:29,951 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:45:30,007 - [Rank0] User network built successfully.
2025-04-18 10:46:00,674 - [Rank0] #################################################################
2025-04-18 10:46:00,674 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:46:00,725 - [Rank0] User network built successfully.
2025-04-18 10:47:15,755 - [Rank0] #################################################################
2025-04-18 10:47:15,755 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:47:15,806 - [Rank0] User network built successfully.
2025-04-18 10:54:45,353 - [Rank0] #################################################################
2025-04-18 10:54:45,353 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:54:45,407 - [Rank0] User network built successfully.
2025-04-18 10:54:45,430 - [Rank0] ERROR: index_copy_(): Expected a long tensor for index, but got Int
2025-04-18 10:54:45,431 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 87, in <module>
    with RandomInputSimulation() as engine:
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 885, in __enter__
    self.initialize()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 961, in initialize
    self.local_circuit.graph_root._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 75, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 76, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 284, in _process
    self._spike_buffer.index_copy_(1, t_idx, spikes.unsqueeze(1))
RuntimeError: index_copy_(): Expected a long tensor for index, but got Int

2025-04-18 10:57:22,695 - [Rank0] #################################################################
2025-04-18 10:57:22,695 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:57:22,740 - [Rank0] User network built successfully.
2025-04-18 10:58:19,557 - [Rank0] #################################################################
2025-04-18 10:58:19,557 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 10:58:19,608 - [Rank0] User network built successfully.
2025-04-18 11:13:28,675 - [Rank0] #################################################################
2025-04-18 11:13:28,675 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:13:28,720 - [Rank0] User network built successfully.
2025-04-18 11:14:05,429 - [Rank0] #################################################################
2025-04-18 11:14:05,429 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:14:05,479 - [Rank0] User network built successfully.
2025-04-18 11:14:16,376 - [Rank0] #################################################################
2025-04-18 11:14:16,376 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:14:16,435 - [Rank0] User network built successfully.
2025-04-18 11:14:34,498 - [Rank0] #################################################################
2025-04-18 11:14:34,498 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:14:34,543 - [Rank0] User network built successfully.
2025-04-18 11:14:59,655 - [Rank0] #################################################################
2025-04-18 11:14:59,655 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:14:59,716 - [Rank0] User network built successfully.
2025-04-18 11:14:59,882 - [Rank0] ERROR: 'RandomSpikeGenerator' object has no attribute 't'
2025-04-18 11:14:59,882 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02.1_oneGPU_profiling.py", line 104, in <module>
    engine.step(prof)
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 981, in step
    self._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 75, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 75, in _call_process
    child._call_process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 76, in _call_process
    self._process()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/../all.py", line 706, in _process
    if group.t % delay_max != delay_max-1:
AttributeError: 'RandomSpikeGenerator' object has no attribute 't'

2025-04-18 11:16:38,560 - [Rank0] #################################################################
2025-04-18 11:16:38,560 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:16:38,647 - [Rank0] User network built successfully.
2025-04-18 11:16:47,363 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 11:16:47,795 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-18 11:16:47,970 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-18 11:20:59,809 - [Rank0] #################################################################
2025-04-18 11:20:59,809 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:20:59,871 - [Rank0] User network built successfully.
2025-04-18 11:21:07,511 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 11:21:07,922 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-18 11:21:08,148 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-18 11:21:41,248 - [Rank0] #################################################################
2025-04-18 11:21:41,248 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:21:41,294 - [Rank0] User network built successfully.
2025-04-18 11:22:46,194 - [Rank0] #################################################################
2025-04-18 11:22:46,195 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:22:46,242 - [Rank0] User network built successfully.
2025-04-18 11:23:12,090 - [Rank0] #################################################################
2025-04-18 11:23:12,090 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:23:12,143 - [Rank0] User network built successfully.
2025-04-18 11:23:44,706 - [Rank0] #################################################################
2025-04-18 11:23:44,706 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:23:44,753 - [Rank0] User network built successfully.
2025-04-18 11:25:47,071 - [Rank0] #################################################################
2025-04-18 11:25:47,071 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:25:47,128 - [Rank0] User network built successfully.
2025-04-18 11:27:06,864 - [Rank0] #################################################################
2025-04-18 11:27:06,864 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:27:06,934 - [Rank0] User network built successfully.
2025-04-18 11:27:37,700 - [Rank0] #################################################################
2025-04-18 11:27:37,701 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:27:37,751 - [Rank0] User network built successfully.
2025-04-18 11:28:32,724 - [Rank0] #################################################################
2025-04-18 11:28:32,724 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:28:32,769 - [Rank0] User network built successfully.
2025-04-18 11:34:24,844 - [Rank0] #################################################################
2025-04-18 11:34:24,844 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:34:24,910 - [Rank0] User network built successfully.
2025-04-18 11:34:49,771 - [Rank0] #################################################################
2025-04-18 11:34:49,772 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:34:49,844 - [Rank0] User network built successfully.
2025-04-18 11:34:57,003 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 11:34:57,359 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-18 11:34:57,517 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-18 11:36:07,152 - [Rank0] #################################################################
2025-04-18 11:36:07,152 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:36:07,212 - [Rank0] User network built successfully.
2025-04-18 11:36:21,052 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 11:36:21,336 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-18 11:36:21,501 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-18 11:36:56,943 - [Rank0] #################################################################
2025-04-18 11:36:56,944 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:36:57,037 - [Rank0] User network built successfully.
2025-04-18 11:37:04,202 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 11:37:04,423 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-18 11:37:04,583 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-18 11:37:49,214 - [Rank0] #################################################################
2025-04-18 11:37:49,215 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:37:49,280 - [Rank0] User network built successfully.
2025-04-18 11:37:56,996 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 11:37:57,373 - [Rank0] Gráfico guardado como 'rank0_output_2.png'
2025-04-18 11:37:57,588 - [Rank0] Gráfico guardado como 'rank0_output_3.png'
2025-04-18 11:41:08,586 - [Rank0] #################################################################
2025-04-18 11:41:08,586 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:41:08,654 - [Rank0] User network built successfully.
2025-04-18 11:41:16,146 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 11:41:16,147 - [Rank0] ERROR: 'RandomInputSimulation' object has no attribute 'voltage_monitor'
2025-04-18 11:41:16,147 - [Rank0] Traceback (most recent call last):
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02_oneGPU.py", line 96, in <module>
    engine.plot_spikes()
  File "/home/alvaro/Desktop/Neurobridge project/neurobridge/examples/lib_example_02_oneGPU.py", line 72, in plot_spikes
    if self.__getattribute__('voltage_monitor'):
AttributeError: 'RandomInputSimulation' object has no attribute 'voltage_monitor'

2025-04-18 11:42:59,376 - [Rank0] #################################################################
2025-04-18 11:42:59,376 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:42:59,426 - [Rank0] User network built successfully.
2025-04-18 11:43:06,936 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 11:43:31,446 - [Rank0] #################################################################
2025-04-18 11:43:31,446 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:43:31,494 - [Rank0] User network built successfully.
2025-04-18 11:43:59,051 - [Rank0] #################################################################
2025-04-18 11:43:59,051 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:43:59,099 - [Rank0] User network built successfully.
2025-04-18 11:45:21,341 - [Rank0] #################################################################
2025-04-18 11:45:21,342 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 11:45:21,440 - [Rank0] User network built successfully.
2025-04-18 13:47:18,327 - [Rank0] #################################################################
2025-04-18 13:47:18,328 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 13:47:18,380 - [Rank0] User network built successfully.
2025-04-18 13:47:19,253 - [Rank0] Gráfico guardado como 'rank0_output.png'
2025-04-18 14:32:49,475 - [Rank0] #################################################################
2025-04-18 14:32:49,475 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:32:49,518 - [Rank0] User network built successfully.
2025-04-18 14:32:50,519 - [Rank0] Gráfico guardado como 'rank0_output.png'
2025-04-18 14:33:17,776 - [Rank0] #################################################################
2025-04-18 14:33:17,776 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:33:17,877 - [Rank0] User network built successfully.
2025-04-18 14:33:31,138 - [Rank0] #################################################################
2025-04-18 14:33:31,138 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:33:31,195 - [Rank0] User network built successfully.
2025-04-18 14:33:53,274 - [Rank0] #################################################################
2025-04-18 14:33:53,274 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:33:53,323 - [Rank0] User network built successfully.
2025-04-18 14:34:04,141 - [Rank0] #################################################################
2025-04-18 14:34:04,141 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:34:04,201 - [Rank0] User network built successfully.
2025-04-18 14:34:13,086 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 14:36:06,469 - [Rank0] #################################################################
2025-04-18 14:36:06,469 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:36:06,524 - [Rank0] User network built successfully.
2025-04-18 14:36:21,314 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 14:43:31,715 - [Rank0] #################################################################
2025-04-18 14:43:31,715 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:43:31,764 - [Rank0] User network built successfully.
2025-04-18 14:43:46,058 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 14:43:53,833 - [Rank0] #################################################################
2025-04-18 14:43:53,833 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:43:53,886 - [Rank0] User network built successfully.
2025-04-18 14:44:11,285 - [Rank0] #################################################################
2025-04-18 14:44:11,286 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:44:11,340 - [Rank0] User network built successfully.
2025-04-18 14:44:26,705 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 14:44:49,756 - [Rank0] #################################################################
2025-04-18 14:44:49,756 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:44:49,808 - [Rank0] User network built successfully.
2025-04-18 14:45:01,708 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
2025-04-18 14:45:10,053 - [Rank0] #################################################################
2025-04-18 14:45:10,053 - [Rank0] Neurobridge initialized. Building user network...
2025-04-18 14:45:10,105 - [Rank0] User network built successfully.
2025-04-18 14:45:21,936 - [Rank0] Gráfico guardado como 'rank0_output_1.png'
